In [1]:
import pandas as pd
import numpy as np
# Load the dataset
df = pd.read_csv("Exact_housing_cleaned_data.csv")
df

df["income_cat"] = pd.cut(df["Median_income"],
                             bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf],
                             labels=[1, 2, 3, 4, 5])

In [2]:
from sklearn.model_selection import StratifiedShuffleSplit
 
# Assume income_cat is a column in the dataset created from median_income
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
 
for train_index, test_index in split.split(df, df
                                           ["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [3]:
df = strat_train_set.copy()
df

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity,income_cat
17051,722,2167,2167,751,-122.06,37.33,7.0102,500001,<1H OCEAN,5
17969,823,3131,3131,888,-117.98,34.07,3.0184,139400,INLAND,3
19243,1098,3527,3527,1170,-117.49,34.04,4.1775,143700,INLAND,3
16456,673,2197,2197,671,-117.65,33.65,7.5426,294800,<1H OCEAN,5
9074,378,905,905,424,-122.29,37.91,5.1691,263200,NEAR BAY,4
...,...,...,...,...,...,...,...,...,...,...
17199,736,1573,1573,819,-122.15,37.73,2.8355,245400,NEAR BAY,2
2148,188,568,568,183,-121.46,38.70,3.8611,93900,INLAND,3
8646,368,1148,1148,344,-118.11,34.06,2.1061,214700,<1H OCEAN,2
12109,466,1586,1586,491,-122.26,38.16,4.0337,130400,NEAR BAY,3
10988,431,962,962,447,-117.04,32.77,2.7826,143800,<1H OCEAN,2

In [4]:
df1 = strat_test_set.copy()
df1

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity,income_cat
17758,794,1900,1900,1157,-117.13,32.63,8.7991,478500,NEAR OCEAN,5
8409,362,805,805,357,-118.41,34.02,3.3462,307000,<1H OCEAN,3
6825,322,765,765,397,-122.48,38.48,4.6379,348200,INLAND,4
8629,367,1102,1102,347,-122.44,37.72,4.3125,267200,NEAR BAY,3
13555,520,1150,1150,529,-122.68,38.43,3.5885,191900,<1H OCEAN,3
...,...,...,...,...,...,...,...,...,...,...
8480,363,1001,1001,362,-122.12,37.88,8.0448,433300,NEAR BAY,5
12582,483,1145,1145,529,-120.47,37.96,2.0060,103000,INLAND,2
3625,241,700,700,292,-117.97,33.68,5.5105,232100,<1H OCEAN,4
12058,464,1187,1187,495,-117.80,34.10,6.2456,161700,INLAND,5
4363,262,1164,1164,274,-118.19,34.04,2.8542,146900,<1H OCEAN,2

In [5]:
housing = strat_train_set.drop("Median_house_value", axis=1)
housing_labels = strat_train_set["Median_house_value"].copy()

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="most_frequent")

housing_num = housing.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='most_frequent')

In [7]:
x = imputer.transform(housing_num)
print(x)
housing_num

[[ 7.2200e+02  2.1670e+03  2.1670e+03 ... -1.2206e+02  3.7330e+01
   7.0102e+00]
 [ 8.2300e+02  3.1310e+03  3.1310e+03 ... -1.1798e+02  3.4070e+01
   3.0184e+00]
 [ 1.0980e+03  3.5270e+03  3.5270e+03 ... -1.1749e+02  3.4040e+01
   4.1775e+00]
 ...
 [ 3.6800e+02  1.1480e+03  1.1480e+03 ... -1.1811e+02  3.4060e+01
   2.1061e+00]
 [ 4.6600e+02  1.5860e+03  1.5860e+03 ... -1.2226e+02  3.8160e+01
   4.0337e+00]
 [ 4.3100e+02  9.6200e+02  9.6200e+02 ... -1.1704e+02  3.2770e+01
   2.7826e+00]]

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income
17051,722,2167,2167,751,-122.06,37.33,7.0102
17969,823,3131,3131,888,-117.98,34.07,3.0184
19243,1098,3527,3527,1170,-117.49,34.04,4.1775
16456,673,2197,2197,671,-117.65,33.65,7.5426
9074,378,905,905,424,-122.29,37.91,5.1691
...,...,...,...,...,...,...,...
17199,736,1573,1573,819,-122.15,37.73,2.8355
2148,188,568,568,183,-121.46,38.70,3.8611
8646,368,1148,1148,344,-118.11,34.06,2.1061
12109,466,1586,1586,491,-122.26,38.16,4.0337
10988,431,962,962,447,-117.04,32.77,2.7826